# fly.toml app configuration file generated for dynamic-discounts on 2025-03-01T09:57:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dynamic-discounts'
primary_region = 'iad'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_discounts,write_products'
  SHOPIFY_API_KEY = '8e19e2cd739b4017001e7c18e0f9c3a7'
  SHOPIFY_APP_URL = 'https://dynamic-discounts.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  internal_port = 3000
  force_https = true
  processes = ["app"]

[[vm]]
  memory = '512Mb'
  cpu_kind = 'shared'
  cpus = 1
