# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e19e2cd739b4017001e7c18e0f9c3a7"
name = "dynamic-discounts"
handle = "dynamic-discounts"
application_url = "https://sur-anger-pounds-super.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://sur-anger-pounds-super.trycloudflare.com/auth/callback",
  "https://sur-anger-pounds-super.trycloudflare.com/auth/shopify/callback",
  "https://sur-anger-pounds-super.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[pos]
embedded = false

[build]
dev_store_url = "codeinspire2.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
