api_version = "2025-01"

[[extensions]]
name = "Product Dynamic Discount extension"
handle = "product-discount"
type = "function"

description = "Create product discount with value taken from a cart attribute. Helper for the setting up Google merchant automated discounts"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/volume-discount/:functionId/new"
  details = "/"
