query RunInput {
  localization {
    language {
      isoCode
    }
  }
  cart {
    attribute {
      key
      value
    }
    lines {
      id
      quantity
      merchandise {
        ... on ProductVariant {
          id
          product {
            title
          }
        }
      }
      attribute(key: "discount-amount") {
        key
        value
      }
    }
  }

  discountNode {
    metafield(
      namespace: "$app:volume-discount"
      key: "function-configuration"
    ) {
      value
    }
  }
}
